### ISSUE TITLE
error occurs when build example because of thrift

### ISSUE THREAD

**Issue by cc5092** [openzipkin/zipkin-go-opentracing#86] opened 2017-11-06 07:36 UTC
I'm trying to build example and run. Found some errors and need help to fix.

When depends on github.com/apache/thrift @ 0.10.0 (which is the lastest version tag). The build result is below
![image](https://user-images.githubusercontent.com/7655917/32429827-624a5af4-c307-11e7-97ce-a5efcf3ee8e9.png)

and then goto line 333 of github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go
![image](https://user-images.githubusercontent.com/7655917/32429870-903031d2-c307-11e7-8674-d9f59ee39cd0.png)

the type of self2.processorMap is thrift.TProcessorFunction. And the definition of thrift.TProcessorFunction in github.com/apache/thrift @ 0.10.0 is below
![image](https://user-images.githubusercontent.com/7655917/32429957-eb1c353c-c307-11e7-83ff-1a1d68bcc008.png)

But the Process function's implemention in scribeProcessorLog is defined like this
![image](https://user-images.githubusercontent.com/7655917/32429992-1920414e-c308-11e7-815e-179b83296285.png)

**Comment by cc5092** [comment] 2017-11-06 09:01
Add another picture by go get github.com/openzipkin/zipkin-go-opentracing

![image](https://user-images.githubusercontent.com/7655917/32432865-02da4450-c314-11e7-91d2-40a7cff3d3b3.png)

**Comment by kujtimiihoxha** [comment] 2017-11-06 12:13
I can confirm ^ also

**Comment by adriancole** [comment] 2017-11-06 13:14
I just kicked off the build again, which indeed breaks
https://travis-ci.org/openzipkin/zipkin-go-opentracing/builds/290589542

Can someone follow-up with this? for example raise a PR?

**Comment by adriancole** [comment] 2017-11-06 13:17
Also a bit curious if folks are actually using the scribe transport or not, or if this is just a problem building the project. For example, if you aren't conflicting because you use thrift, perhaps there's a way to not use the trunk version of thrift.

(I have no idea what dependency hygiene looks like in go world, so forgive me in advance if this isn't a relevant suggestion)

**Comment by kujtimiihoxha** [comment] 2017-11-06 13:35
I am not using thrift at all, it is just a problem while building. (I am using go-kit, it uses this library)

**Comment by kujtimiihoxha** [comment] 2017-11-06 13:43
@adriancole  here you go https://github.com/openzipkin/zipkin-go-opentracing/pull/87

**Comment by jcchavezs** [comment] 2017-11-06 15:56
This PR solves the actual problem https://github.com/openzipkin/zipkin-go-opentracing/pull/88

@adriancole @basvanbeek

**Comment by sitano** [comment] 2017-11-07 15:00
it's a shame it depends on some middle version in between thrift 0.11.0 and the latest, and it does not compatible to either one

**Comment by AndreaM16** [comment] 2017-11-07 15:08
When will it be merged? I really need this issue to get fixed. I cannot run any go-kit example.

**Comment by sitano** [comment] 2017-11-07 15:09
@AndreaM16 you can fix it pinning thrift version in your deps (glide or whatever) to something working like:
```
- package: github.com/apache/thrift
  version: a533ea1615e9df935e77b99440cf264c6b417e3e
```

**Comment by jcchavezs** [comment] 2017-11-07 15:26
@AndreaM16 you can go to your `$GOPATH/src/github.com/apache/thrift` and there do `git checkout a533ea1615e9df935e77b99440cf264c6b417e3e`. Another solution is [this one](https://github.com/openzipkin/zipkin-go-opentracing/pull/88) which is waiting to be merged.

**Comment by AndreaM16** [comment] 2017-11-07 15:28
Solved, thanks guys.

**Comment by basvanbeek** [comment] 2017-11-08 12:16
updated the generated thrift code in #90 and tests pass again

**Closed by basvanbeek** 2017-11-08 12:16 UTC
