### ISSUE TITLE
Master build failed

### ISSUE THREAD

**Issue by liyichao** [openzipkin/zipkin-go-opentracing#49] opened 2017-02-13 06:31 UTC
It reports
```
# github.com/openzipkin/zipkin-go-opentracing/wire
../../../github.com/openzipkin/zipkin-go-opentracing/wire/wire.pb.go:31: undefined: proto.GoGoProtoPackageIsVersion2
../../../github.com/openzipkin/zipkin-go-opentracing/wire/wire.pb.go:98: undefined: proto.RegisterType
../../../github.com/openzipkin/zipkin-go-opentracing/wire/wire.pb.go:624: undefined: proto.RegisterFile
```

**Comment by basvanbeek** [comment] 2017-02-13 11:16
have you installed the gogo/protobuf tooling and is it up to date?

try this: go get -u github.com/gogo/protobuf/protoc-gen-gogofaster

dupe of #46

**Closed** 2017-02-19 09:05 UTC

**Comment by liyichao** [comment] 2017-02-22 03:19
I failed to run the command, it reports:
```
package github.com/gogo/protobuf/protoc-gen-gogofaster
	imports github.com/gogo/protobuf/vanity/command
	imports github.com/gogo/protobuf/protoc-gen-gogo/internal/grpc: use of internal package not allowed
```

**Comment by basvanbeek** [comment] 2017-02-22 12:24
That might not be a problem. You at least pulled in the GogoProtobuf package and should be able to compile your code which uses zipkin-go-opentracing. 

If this still gives issues, am I right to assume you're trying to vendor your application? Make sure you flatten vendoring or you'll run into these kind of issues.
