### ISSUE TITLE
api/vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:286: assignment count mismatch: 2 = 1

### ISSUE THREAD

**Issue by arthurgustin** [openzipkin/zipkin-go-opentracing#89] opened 2017-11-07 12:31 UTC
Hi, got this message while updating dependancies with glide:

`api/vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:286: assignment count mismatch: 2 = 1
`

**Comment by sitano** [comment] 2017-11-07 15:02
dupe of #86

**Closed** 2017-11-08 11:39 UTC
